[package]
name    = "cw20-multibalance"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
cosmwasm-schema = { version = "1.5" }
cosmwasm-std    = { version = "1.5.4", features = ["stargate"] }
cw-storage-plus = { version = "1.2" }
ethabi          = { workspace = true }
thiserror       = { workspace = true }
