[package]
name    = "ibc-union"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
alloy-sol-types = { workspace = true }
bincode         = { workspace = true, features = ["alloc", "derive"] }
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true, features = ["abort", "iterator"] }
depolama        = { workspace = true }
embed-commit    = { workspace = true }
ethabi          = { workspace = true }
frissitheto     = { workspace = true }
hex             = { workspace = true }
ibc-union-msg   = { workspace = true }
ibc-union-spec  = { workspace = true, features = ["ethabi", "serde", "bincode"] }
serde           = { workspace = true, features = ["derive"] }
serde-json-wasm = "1.0"
strum           = { version = "0.26.3", features = ["derive"] }
thiserror       = { workspace = true }
unionlabs       = { workspace = true, features = ["ethabi", "bincode"] }

[dev-dependencies]
hex-literal.workspace = true
