[package]
name    = "voyager-client-module-sui"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
embed-commit           = { workspace = true }
jsonrpsee              = { workspace = true, features = ["macros", "server", "tracing"] }
serde                  = { workspace = true, features = ["derive"] }
serde_json             = { workspace = true }
sui-light-client-types = { workspace = true, features = ["serde", "ethabi", "bincode"] }
thiserror              = { workspace = true }
tokio                  = { workspace = true }
tracing                = { workspace = true }
unionlabs              = { workspace = true, features = ["bincode"] }
voyager-message        = { workspace = true }
