[package]
authors.workspace      = true
edition.workspace      = true
license-file.workspace = true
name                   = "sui-light-client"
publish.workspace      = true
repository.workspace   = true
version                = "0.0.0"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bcs                    = { workspace = true }
bincode                = { workspace = true }
blake2                 = "0.10.6"
cosmwasm-std           = { workspace = true, features = ["abort", "cosmwasm_2_1"] }
depolama               = { workspace = true }
embed-commit           = { workspace = true }
frissitheto            = { workspace = true }
ibc-union-light-client = { workspace = true }
ibc-union-msg          = { workspace = true }
serde                  = { workspace = true, features = ["derive"] }
serde_repr             = { version = "0.1.20", optional = true }
sui-light-client-types = { workspace = true, features = ["bincode", "ethabi", "serde"] }
sui-verifier           = { workspace = true }
thiserror              = { workspace = true }
typenum                = { version = "1.17.0", default-features = false }
unionlabs              = { workspace = true, features = ["ethabi"] }

[dev-dependencies]
hex-literal          = { workspace = true }
serde_json           = { workspace = true }
unionlabs-primitives = { workspace = true, features = ["base64"] }

[features]
library = []
