[package]
authors.workspace      = true
edition.workspace      = true
license-file.workspace = true
name                   = "sui-light-client"
publish.workspace      = true
repository.workspace   = true
version                = "0.0.0"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bincode                = { workspace = true }
cosmwasm-std           = { workspace = true, features = ["abort", "cosmwasm_2_1"] }
depolama               = { workspace = true }
embed-commit           = { workspace = true }
frissitheto            = { workspace = true }
ibc-union-light-client = { workspace = true }
ibc-union-msg          = { workspace = true }
serde                  = { workspace = true, features = ["derive"] }
sui-light-client-types = { workspace = true, features = ["bincode", "ethabi", "serde"] }
thiserror              = { workspace = true }
unionlabs              = { workspace = true, features = ["ethabi"] }
bcs = { workspace = true }
serde_repr = { version = "0.1.20", optional = true }
blake2               = "0.10.6"
typenum              = { version = "1.17.0", default-features = false }
sui-verifier = { workspace = true }

[dev-dependencies]
hex-literal = { workspace = true }
unionlabs-primitives = { workspace = true, features = ["base64"]}
serde_json = { workspace = true }

[features]
library = []
